{% set python_min = "3.11" %}
{% set name = "meteor-maps" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/meteor_maps-{{ version }}.tar.gz
  sha256: 2110a5e1f0f41928bd7677180ba9aa7ce35f086d7614deaa5aa3c0789bca6e9b

build:
  entry_points:
    - meteor.diffmap = meteor.scripts.diffmap:main
    - meteor.phaseboost = meteor.scripts.phaseboost:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26
    - scipy >=1.14.0
    - gemmi ==0.6.6
    - scikit-image >=0.24.0
    - reciprocalspaceship >=1.0.2
    - structlog >=24.4.0
    - pydantic >=2.10.0

test:
  source_files:
    - meteor/
    - test/
  imports:
    - meteor
  commands:
    - pip check
    - meteor.diffmap --help
    - meteor.phaseboost --help
    - pytest ./test
  requires:
    - python {{ python_min }}
    - pip
    - pytest

about:
  home: https://pypi.org/project/meteor-maps
  summary: denoise crystallographic difference maps
  dev_url: https://github.com/rs-station/meteor
  doc_url: https://rs-station.github.io/meteor/
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tjlane
    - alisiafadini
